### ISSUE TITLE
Error while installing player, No such file or directory  #include "interface_table.h"

### ISSUE THREAD

**Issue by behroozmrd47** [playerproject/player#13]
I am trying to install Player 3.1.0 on Ubuntu 18.04 and following error shows up:
I was wondering if I am missing any specific dependencies or how to solve this issue.
Any help is greatly appreciated.

[  1%] Built target playercommon
[  1%] Generating functiontable_gen.h
[  2%] Built target functiontable_gen
[  3%] Generating player_interfaces.h
[  3%] Built target player_interfaces
[  3%] Building C object libplayerinterface/CMakeFiles/playerinterface.dir/interface_util.o
/home/neuwong/RobSofts/player-release-3-1-0/libplayerinterface/interface_util.c:51:10: fatal error: interface_table.h: No such file or directory
 #include "interface_table.h"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
libplayerinterface/CMakeFiles/playerinterface.dir/build.make:273: recipe for target 'libplayerinterface/CMakeFiles/playerinterface.dir/interface_util.o' failed
make[2]: *** [libplayerinterface/CMakeFiles/playerinterface.dir/interface_util.o] Error 1
CMakeFiles/Makefile2:254: recipe for target 'libplayerinterface/CMakeFiles/playerinterface.dir/all' failed
make[1]: *** [libplayerinterface/CMakeFiles/playerinterface.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by richmattes** [comment]
I think this problem stems from the target dependencies in CMake not being set up properly.  I believe it's fixed in the current git master branch, if you want to give that a try.  If it works for you I'll prepare a 3.1.1 release (there's been a few other fixes that have been pushed since 3.1.0 to deal with changes in system dependencies).

**Comment by behroozmrd47** [comment]
Hey,

Thanks for coming back. I did install Player by downloading the git and it was solved.

Thanks,
